---
- name: Set up DNF-Automatic
  hosts: all
  become: true
  gather_facts: false

  tasks:

    - name: Install dnf-automatic
      ansible.builtin.dnf:
        name: dnf-automatic
        state: present

    - name: Enable and Start dnf-automatic
      ansible.builtin.systemd:
        name: dnf-automatic.timer
        enabled: true
        state: started

    - name: Configure dnf-automatic
      ansible.builtin.copy:
        dest: /etc/dnf/automatic.conf
        content: |
          [commands]
          upgrade_type = security
          apply_updates = yes
          [emitters]
          system_name = automated-updater
          emit_via = motd
          [base]
          debuglevel = 1
        mode: '0640'
      notify: Restart dnf-automatic

    - name: Verify dnf-automatic status
      ansible.builtin.command: systemctl list-timers dnf-automatic.timer
      register: dnf_automatic_status
      ignore_errors: true
      changed_when: true

    - name: Display dnf-automatic.timer status
      ansible.builtin.debug:
        msg: "{{ dnf_automatic_status.stdout }}"

  handlers:

    - name: Restart dnf-automatic
      ansible.builtin.systemd:
        name: dnf-automatic.timer
        state: restarted
